class CitizenStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'ResQShield',
      'citizenPortal': 'Citizen Safety Portal',
      'safeRoutesTagline': 'Safer Routes • Stronger Communities',
      'normalStatus': 'NORMAL',
      'warningStatus': 'WARNING',
      'evacuateStatus': 'EVACUATION RECOMMENDED',
      'normalDesc': 'River levels are within safe limits. No immediate threat detected.',
      'warningDesc': 'Heavy rainfall upstream. River surge anticipated in low-lying zones.',
      'evacuateDesc': 'Water entering residential sector. Move to designated high ground shelters immediately.',
      'myRisk': 'My Risk',
      'safeRoute': 'Safe Route',
      'shelters': 'Shelters',
      'sosHelp': '🆘 SOS / HELP',
      'reportHazard': 'Report Hazard',
      'alertInbox': 'Alert Inbox',
      'offlineBanner': 'Offline Mode • Last verified update 3 mins ago via LoRa mesh cache',
      'startSafeRoute': 'START SAFE ROUTE',
      'nearestShelter': 'Nearest Safe Shelter',
      'distance': 'away',
      'capacity': 'Capacity',
      'doctorOnSite': 'Medical Doctor On-Site',
      'emergencyCall': 'Emergency Helplines',
      'changeRole': 'Change Role',
      'getOtp': 'Get OTP',
      'verifyOtp': 'Verify & Proceed',
      'grantPermission': 'Grant GPS Location Access',
    },
    'hi': {
      'appName': 'रेसक्यू-शील्ड',
      'citizenPortal': 'नागरिक सुरक्षा पोर्टल',
      'safeRoutesTagline': 'सुरक्षित मार्ग • सशक्त समुदाय',
      'normalStatus': 'सामान्य',
      'warningStatus': 'सतर्कता चेतावनी',
      'evacuateStatus': 'तत्काल सुरक्षित स्थल जाएं',
      'normalDesc': 'नदी का जलस्तर सुरक्षित सीमा में है। वर्तमान में कोई तात्कालिक खतरा नहीं है।',
      'warningDesc': 'ऊपरी जलग्रहण क्षेत्र में भारी बारिश। निचले इलाकों में जलभराव की संभावना।',
      'evacuateDesc': 'रिहायशी इलाकों में पानी बढ़ रहा है। कृपया तुरंत नजदीकी राहत शिविर में पहुंचें।',
      'myRisk': 'मेरा जोखिम',
      'safeRoute': 'सुरक्षित मार्ग',
      'shelters': 'राहत शिविर',
      'sosHelp': '🆘 आपातकालीन मदद',
      'reportHazard': 'खतरा दर्ज करें',
      'alertInbox': 'अलर्ट्स इनबॉक्स',
      'offlineBanner': 'ऑफलाइन मोड • अंतिम सत्यापित अपडेट 3 मिनट पहले (लोरा मेश कैश)',
      'startSafeRoute': 'सुरक्षित मार्ग शुरू करें',
      'nearestShelter': 'नजदीकी सुरक्षित शिविर',
      'distance': 'दूरी',
      'capacity': 'क्षमता',
      'doctorOnSite': 'डॉक्टर व प्राथमिक चिकित्सा उपलब्ध',
      'emergencyCall': 'आपातकालीन हेल्पलाइन',
      'changeRole': 'भूमिका बदलें',
      'getOtp': 'ओटीपी प्राप्त करें',
      'verifyOtp': 'सत्यापित करें और आगे बढ़ें',
      'grantPermission': 'जीपीएस लोकेशन अनुमति दें',
    },
  };

  static String get(String key, {bool isHindi = false}) {
    final lang = isHindi ? 'hi' : 'en';
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
